sources_ref = {
    "book_000.pdf": "Frankl, V. E. (2006). Man’s Search for Meaning. Beacon Press.",
    "book_001.pdf": "Frankl, V. E., Winston, C., & Winston, R. (2019). The Doctor and the Soul: From Psychotherapy to Logotherapy. Vintage Books.",
    "book_002.pdf": "Frankl, V. E. (2004). On the Theory and Therapy of Mental Disorders: An Introduction to Logotherapy and Existential Analysis. Brunner-Routledge.",
    "book_003.pdf": "Frankl, V. E., & Crumbaugh, J. C. (1967). Psychotherapy and Existentialism. Simon & Schuster.",
    "book_004.pdf": "Frankl, V. E. (1988). The Will to Meaning: Foundations and Applications of Logotherapy. Penguin.",
    "book_005.pdf": "Frankl, V. E. (2002). The Unheard Cry for Meaning: Psychotherapy and Humanism. Washington Square Press/Pocket Books.",
    "book_006.pdf": "Frankl, V. E. (2008). Recollections: An Autobiography. Basic Books.",
    "book_007.pdf": "Frankl, V. E., & Emil, V. (1997). Man’s Search for Ultimate Meaning. Insight Books.",
    "book_008.pdf": "Frankl, V. E., Goleman, D., & Franz Vesely. (2020). Yes to Life : In Spite of Everything. Beacon Press.",
    "journal_002_1.txt": "Journal of Search for Meaning, Volume 02 Number 1 (Spring 1979) The International Forum for Logotherapy.",
    "journal_002_2.txt": "Journal of Search for Meaning, Volume 02 Number 2 (Autumn 1979) The International Forum for Logotherapy.",
    "journal_003_1.txt": "Journal of Search for Meaning, Volume 03 Number 1 (Spring 1980) The International Forum for Logotherapy.",
    "journal_003_2.txt": "Journal of Search for Meaning, Volume 03 Number 2 (Autumn 1980) The International Forum for Logotherapy.",
    "journal_004_1.txt": "Journal of Search for Meaning, Volume 04 Number 1 (Spring 1981) The International Forum for Logotherapy.",
    "journal_004_2.txt": "Journal of Search for Meaning, Volume 04 Number 2 (Autumn 1981) The International Forum for Logotherapy.",
    "journal_005_1.txt": "Journal of Search for Meaning, Volume 05 Number 1 (Spring 1982) The International Forum for Logotherapy.",
    "journal_005_2.txt": "Journal of Search for Meaning, Volume 05 Number 2 (Autumn 1982) The International Forum for Logotherapy.",
    "journal_006_1.txt": "Journal of Search for Meaning, Volume 06 Number 1 (Spring 1983) The International Forum for Logotherapy.",
    "journal_006_2.txt": "Journal of Search for Meaning, Volume 06 Number 2 (Autumn 1983) The International Forum for Logotherapy.",
    "journal_007_1.txt": "Journal of Search for Meaning, Volume 07 Number 1 (Spring 1984) The International Forum for Logotherapy.",
    "journal_007_2.txt": "Journal of Search for Meaning, Volume 07 Number 2 (Autumn 1984) The International Forum for Logotherapy.",
    "journal_008_1.txt": "Journal of Search for Meaning, Volume 08 Number 1 (Spring 1985) The International Forum for Logotherapy.",
    "journal_008_2.txt": "Journal of Search for Meaning, Volume 08 Number 2 (Autumn 1985) The International Forum for Logotherapy.",
    "journal_009_1.txt": "Journal of Search for Meaning, Volume 09 Number 1 (Spring 1986) The International Forum for Logotherapy.",
    "journal_009_2.txt": "Journal of Search for Meaning, Volume 09 Number 2 (Autumn 1986) The International Forum for Logotherapy.",
    "journal_010_1.txt": "Journal of Search for Meaning, Volume 10 Number 1 (Spring 1987) The International Forum for Logotherapy.",
    "journal_010_2.txt": "Journal of Search for Meaning, Volume 10 Number 2 (Autumn 1987) The International Forum for Logotherapy.",
    "journal_011_1.txt": "Journal of Search for Meaning, Volume 11 Number 1 (Spring 1988) The International Forum for Logotherapy.",
    "journal_011_2.txt": "Journal of Search for Meaning, Volume 11 Number 2 (Autumn 1988) The International Forum for Logotherapy.",
    "journal_012_1.txt": "Journal of Search for Meaning, Volume 12 Number 1 (Spring 1989) The International Forum for Logotherapy.",
    "journal_012_2.txt": "Journal of Search for Meaning, Volume 12 Number 2 (Autumn 1989) The International Forum for Logotherapy.",
    "journal_013_1.txt": "Journal of Search for Meaning, Volume 13 Number 1 (Spring 1990) The International Forum for Logotherapy.",
    "journal_013_2.txt": "Journal of Search for Meaning, Volume 13 Number 2 (Autumn 1990) The International Forum for Logotherapy.",
    "journal_014_1.txt": "Journal of Search for Meaning, Volume 14 Number 1 (Spring 1991) The International Forum for Logotherapy.",
    "journal_014_2.txt": "Journal of Search for Meaning, Volume 14 Number 2 (Autumn 1991) The International Forum for Logotherapy.",
    "journal_015_1.txt": "Journal of Search for Meaning, Volume 15 Number 1 (Spring 1992) The International Forum for Logotherapy.",
    "journal_015_2.txt": "Journal of Search for Meaning, Volume 15 Number 2 (Autumn 1992) The International Forum for Logotherapy.",
    "journal_016_1.txt": "Journal of Search for Meaning, Volume 16 Number 1 (Spring 1993) The International Forum for Logotherapy.",
    "journal_016_2.txt": "Journal of Search for Meaning, Volume 16 Number 2 (Autumn 1993) The International Forum for Logotherapy.",
    "journal_017_1.txt": "Journal of Search for Meaning, Volume 17 Number 1 (Spring 1994) The International Forum for Logotherapy.",
    "journal_017_2.txt": "Journal of Search for Meaning, Volume 17 Number 2 (Autumn 1994) The International Forum for Logotherapy.",
    "journal_018_1.txt": "Journal of Search for Meaning, Volume 18 Number 1 (Spring 1995) The International Forum for Logotherapy.",
    "journal_018_2.txt": "Journal of Search for Meaning, Volume 18 Number 2 (Autumn 1995) The International Forum for Logotherapy.",
    "journal_019_1.txt": "Journal of Search for Meaning, Volume 19 Number 1 (Spring 1996) The International Forum for Logotherapy.",
    "journal_019_2.txt": "Journal of Search for Meaning, Volume 19 Number 2 (Autumn 1996) The International Forum for Logotherapy.",
    "journal_020_1.txt": "Journal of Search for Meaning, Volume 20 Number 1 (Spring 1997) The International Forum for Logotherapy.",
    "journal_020_2.txt": "Journal of Search for Meaning, Volume 20 Number 2 (Autumn 1997) The International Forum for Logotherapy.",
    "journal_021_1.txt": "Journal of Search for Meaning, Volume 21 Number 1 (Spring 1998) The International Forum for Logotherapy.",
    "journal_021_2.txt": "Journal of Search for Meaning, Volume 21 Number 2 (Autumn 1998) The International Forum for Logotherapy.",
    "journal_022_1.txt": "Journal of Search for Meaning, Volume 22 Number 1 (Spring 1999) The International Forum for Logotherapy.",
    "journal_022_2.txt": "Journal of Search for Meaning, Volume 22 Number 2 (Autumn 1999) The International Forum for Logotherapy.",
    "journal_023_1.txt": "Journal of Search for Meaning, Volume 23 Number 1 (Spring 2000) The International Forum for Logotherapy.",
    "journal_023_2.txt": "Journal of Search for Meaning, Volume 23 Number 2 (Autumn 2000) The International Forum for Logotherapy.",
    "journal_024_1.txt": "Journal of Search for Meaning, Volume 24 Number 1 (Spring 2001) The International Forum for Logotherapy.",
    "journal_024_2.txt": "Journal of Search for Meaning, Volume 24 Number 2 (Autumn 2001) The International Forum for Logotherapy.",
    "journal_025_1.txt": "Journal of Search for Meaning, Volume 25 Number 1 (Spring 2002) The International Forum for Logotherapy.",
    "journal_025_2.txt": "Journal of Search for Meaning, Volume 25 Number 2 (Autumn 2002) The International Forum for Logotherapy.",
    "journal_026_1.txt": "Journal of Search for Meaning, Volume 26 Number 1 (Spring 2003) The International Forum for Logotherapy.",
    "journal_026_2.txt": "Journal of Search for Meaning, Volume 26 Number 2 (Autumn 2003) The International Forum for Logotherapy.",
    "journal_027_1.txt": "Journal of Search for Meaning, Volume 27 Number 1 (Spring 2004) The International Forum for Logotherapy.",
    "journal_027_2.txt": "Journal of Search for Meaning, Volume 27 Number 2 (Autumn 2004) The International Forum for Logotherapy.",
    "journal_028_1.txt": "Journal of Search for Meaning, Volume 28 Number 1 (Spring 2005) The International Forum for Logotherapy.",
    "journal_028_2.txt": "Journal of Search for Meaning, Volume 28 Number 2 (Autumn 2005) The International Forum for Logotherapy.",
    "journal_029_1.txt": "Journal of Search for Meaning, Volume 29 Number 1 (Spring 2006) The International Forum for Logotherapy.",
    "journal_029_2.txt": "Journal of Search for Meaning, Volume 29 Number 2 (Autumn 2006) The International Forum for Logotherapy.",
    "journal_030_1.txt": "Journal of Search for Meaning, Volume 30 Number 1 (Spring 2007) The International Forum for Logotherapy.",
    "journal_030_2.txt": "Journal of Search for Meaning, Volume 30 Number 2 (Autumn 2007) The International Forum for Logotherapy.",
    "journal_031_1.txt": "Journal of Search for Meaning, Volume 31 Number 1 (Spring 2008) The International Forum for Logotherapy.",
    "journal_031_2.txt": "Journal of Search for Meaning, Volume 31 Number 2 (Autumn 2008) The International Forum for Logotherapy.",
    "journal_032_1.txt": "Journal of Search for Meaning, Volume 32 Number 1 (Spring 2009) The International Forum for Logotherapy.",
    "journal_032_2.txt": "Journal of Search for Meaning, Volume 32 Number 2 (Autumn 2009) The International Forum for Logotherapy.",
    "journal_033_1.txt": "Journal of Search for Meaning, Volume 33 Number 1 (Spring 2010) The International Forum for Logotherapy.",
    "journal_033_2.txt": "Journal of Search for Meaning, Volume 33 Number 2 (Autumn 2010) The International Forum for Logotherapy.",
    "journal_034_1.pdf": "Journal of Search for Meaning, Volume 34 Number 1 (Spring 2011) The International Forum for Logotherapy.",
    "journal_034_2.pdf": "Journal of Search for Meaning, Volume 34 Number 2 (Autumn 2011) The International Forum for Logotherapy.",
    "journal_035_1.pdf": "Journal of Search for Meaning, Volume 35 Number 1 (Spring 2012) The International Forum for Logotherapy.",
    "journal_035_2.pdf": "Journal of Search for Meaning, Volume 35 Number 2 (Autumn 2012) The International Forum for Logotherapy.",
    "journal_036_1.pdf": "Journal of Search for Meaning, Volume 36 Number 1 (Spring 2013) The International Forum for Logotherapy.",
    "journal_036_2.pdf": "Journal of Search for Meaning, Volume 36 Number 2 (Autumn 2013) The International Forum for Logotherapy.",
    "journal_037_1.pdf": "Journal of Search for Meaning, Volume 37 Number 1 (Spring 2014) The International Forum for Logotherapy.",
    "journal_037_2.pdf": "Journal of Search for Meaning, Volume 37 Number 2 (Autumn 2014) The International Forum for Logotherapy.",
    "journal_038_1.pdf": "Journal of Search for Meaning, Volume 38 Number 1 (Spring 2015) The International Forum for Logotherapy.",
    "journal_038_2.pdf": "Journal of Search for Meaning, Volume 38 Number 2 (Autumn 2015) The International Forum for Logotherapy.",
    "journal_039_1.pdf": "Journal of Search for Meaning, Volume 39 Number 1 (Spring 2016) The International Forum for Logotherapy.",
    "journal_039_2.pdf": "Journal of Search for Meaning, Volume 39 Number 2 (Autumn 2016) The International Forum for Logotherapy.",
    "journal_040_1.pdf": "Journal of Search for Meaning, Volume 40 Number 1 (Spring 2017) The International Forum for Logotherapy.",
    "journal_040_2.pdf": "Journal of Search for Meaning, Volume 40 Number 2 (Autumn 2017) The International Forum for Logotherapy.",
    "journal_041_1.pdf": "Journal of Search for Meaning, Volume 41 Number 1 (Spring 2018) The International Forum for Logotherapy.",
    "journal_041_2.pdf": "Journal of Search for Meaning, Volume 41 Number 2 (Autumn 2018) The International Forum for Logotherapy.",
    "journal_042_1.pdf": "Journal of Search for Meaning, Volume 42 Number 1 (Spring 2019) The International Forum for Logotherapy.",
    "journal_042_2.pdf": "Journal of Search for Meaning, Volume 42 Number 2 (Autumn 2019) The International Forum for Logotherapy.",
    "journal_043_1.pdf": "Journal of Search for Meaning, Volume 43 Number 1 (Spring 2020) The International Forum for Logotherapy.",
    "journal_043_2.pdf": "Journal of Search for Meaning, Volume 43 Number 2 (Autumn 2020) The International Forum for Logotherapy.",
    "journal_044_1.pdf": "Journal of Search for Meaning, Volume 44 Number 1 (Spring 2021) The International Forum for Logotherapy.",
    "journal_044_2.pdf": "Journal of Search for Meaning, Volume 44 Number 2 (Autumn 2021) The International Forum for Logotherapy.",
    "journal_045_1.pdf": "Journal of Search for Meaning, Volume 45 Number 1 (Spring 2022) The International Forum for Logotherapy.",
    "journal_045_2.pdf": "Journal of Search for Meaning, Volume 45 Number 2 (Autumn 2022) The International Forum for Logotherapy.",
    "journal_046_1.pdf": "Journal of Search for Meaning, Volume 46 Number 1 (Spring 2023) The International Forum for Logotherapy.",
    "journal_046_2.pdf": "Journal of Search for Meaning, Volume 46 Number 2 (Autumn 2023) The International Forum for Logotherapy.",
}
